# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ghana Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: staging
remotedatabaseurl: "https://sustainabledevelopment-ghana.github.io/sdg-data"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_json:
  - data: meta
    json: 'https://sustainabledevelopment-ghana.github.io/sdg-data/meta/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://sustainabledevelopment-ghana.github.io/sdg-data/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://sustainabledevelopment-ghana.github.io/sdg-data/meta/schema.json'
  - data: translations
    # Pin to version of the translation repository.
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.4.0.json'

analytics:
  ga_prod: ''

# Social media accounts.
twitter: 'StatsGhana'

###################################################################################################
email_contacts:
  questions: sdg.secretariat@statsghana.gov.gh
  suggestions: sdg.secretariat@statsghana.gov.gh
  functional: sdg.secretariat@statsghana.gov.gh
###################################################################################################

# Github Repo for Data
repo_name: sdg-data
branch: develop
org_name: sustainabledevelopment-ghana

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Ghanaian
  adjective: Ghanaian

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# The list of languages that are translated. The first one is the default.
languages:
  - en

goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Menu
menu:
 # Use these to customise the main navigation.
 - path: /
   translation_key: general.goals
 - path: /reporting-status/
   translation_key: menu.reporting_status
 - path: /about/
   translation_key: menu.about
 - path: /publications/
   translation_key: menu.publications
 - path: /guidance/
   translation_key: menu.guidance
 - path: /faq/
   translation_key: menu.faq

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

remote_theme: open-sdg/open-sdg@0.4.0

# Mapping
#map_options:
#  tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
#  tileOptions:
#    id: mapbox.light
#    accessToken: pk.eyJ1IjoiYnJvY2tmYW5uaW5nMSIsImEiOiJjaXplbmgzczgyMmRtMnZxbzlmbGJmdW9pIn0.LU-BYMX69uu3eGgk0Imibg
#    attribution: <a href="https://www.mapbox.com">Mapbox</a> | <a href="http://geoportal.statistics.gov.uk/">ONS</a>
#  noValueColor: #7c7c7c
#  minZoom: 8
#map_layers:
  #Province
#  - min_zoom: 8
#    max_zoom: 10
#    serviceUrl: TBC
#    nameProperty: Prov_Name
#    idProperty: Prov_ID
#    staticBorders: true
     link: TBC
  #District
#  - min_zoom: 9
#    max_zoom: 10
#    serviceUrl: TBC
#    nameProperty: District
#    idProperty: Dist_ID
#    staticBorders: false
#    link: TBC